
services:
  ical-urenberekening:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./exports:/app/exports
    environment:
      - FLASK_ENV=production

