name: Build and Push Docker Image to GHCR

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # Zorg dat 'packages: write' is toegevoegd, hiermee kan je naar GHCR pushen
    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the GitHub Container Registry
        run: echo "${{ github.token }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push
        run: |
          docker build -t ghcr.io/${{ github.actor }}/timetracker:latest .
          docker push ghcr.io/${{ github.actor }}/timetracker:latest
